### ISSUE TITLE
Segmentation Fault Pyroscope ruby gem

### ISSUE THREAD

**Issue by infl-herman** [pyroscope-io/pyroscope-rs#59]
**Describe the bug you encountered:**

Getting segmentation fault when running Pyroscope on a Rails app

**What did you expect to happen instead?**

No Segementatin fault

**How did you install `pyroscope-rs`?**

Using a Gemfile
```
gem 'pyroscope', '~> 0.4.0
```

---

**pyroscope-rs version and environment**
Gem version installed: 0.4.0, running on a docker image, here is the docker file on the base image.

```
FROM ruby:2.5.5

RUN apt update -y && apt install -y \
  dnsutils \
  less \
  tzdata \
  libxml2-dev \
  libxslt1-dev \
  libstdc++-8-dev \
  imagemagick \
  potrace \
  postgresql-client \
  postgresql \
  file \
  libxml2-dev \
  libxslt-dev \
  linux-libc-dev \
  sqlite3 \
  libsqlite3-dev

RUN bundle config build.nokogiri --use-system-libraries
```

this is the app's docker file
```
FROM <company docker registry>/docker/ruby:2.5.5

WORKDIR /usr/src/app

RUN apt update -y && apt install -y shared-mime-info musl-dev
RUN ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

ENV BUNDLE_PATH=/opt/bundle \
    BUNDLE_DISABLE_SHARED_GEMS='1' \
    PATH="/opt/bundle/bin:${PATH}"
```

and here is the segfault info we get when we run our rails app:

```
Puma starting in single mode...
* Version 5.0.4 (ruby 2.5.5-p157), codename: Spoony Bard
* Min threads: 8, max threads: 8
* Environment: development
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
/opt/bundle/gems/faraday-0.9.2/lib/faraday/upload_io.rb:65: warning: constant ::UploadIO is deprecated
/opt/bundle/gems/faraday-0.9.2/lib/faraday/upload_io.rb:66: warning: constant ::Parts is deprecated
/usr/src/app/config/application.rb:233: warning: already initialized constant Twitter::Validation::MAX_LENGTH
/opt/bundle/gems/twitter-text-1.14.7/lib/twitter-text/validation.rb:5: warning: previous definition of MAX_LENGTH was here
Influitive AdvocateHub version HEAD
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
{"_schema":"infl:log:2.0","source":"unknown","service":"UNDEFINED-SERVICE","host":"27e34d1e8dfa","tag":"log","level":"INFO","time":"2022-08-28T07:26:19.723Z","message":"(0.003976s) SELECT \"pg_attribute\".\"attname\" AS \"name\", CAST(\"pg_attribute\".\"atttypid\" AS integer) AS \"oid\", CAST(\"basetype\".\"oid\" AS integer) AS \"base_oid\", format_type(\"basetype\".\"oid\", \"pg_type\".\"typtypmod\") AS \"db_base_type\", format_type(\"pg_type\".\"oid\", \"pg_attribute\".\"atttypmod\") AS \"db_type\", pg_get_expr(\"pg_attrdef\".\"adbin\", \"pg_class\".\"oid\") AS \"default\", NOT \"pg_attribute\".\"attnotnull\" AS \"allow_null\", COALESCE((\"pg_attribute\".\"attnum\" = ANY(\"pg_index\".\"indkey\")), false) AS \"primary_key\" FROM \"pg_class\" INNER JOIN \"pg_attribute\" ON (\"pg_attribute\".\"attrelid\" = \"pg_class\".\"oid\") INNER JOIN \"pg_type\" ON (\"pg_type\".\"oid\" = \"pg_attribute\".\"atttypid\") LEFT OUTER JOIN \"pg_type\" AS \"basetype\" ON (\"basetype\".\"oid\" = \"pg_type\".\"typbasetype\") LEFT OUTER JOIN \"pg_attrdef\" ON ((\"pg_attrdef\".\"adrelid\" = \"pg_class\".\"oid\") AND (\"pg_attrdef\".\"adnum\" = \"pg_attribute\".\"attnum\")) LEFT OUTER JOIN \"pg_index\" ON ((\"pg_index\".\"indrelid\" = \"pg_class\".\"oid\") AND (\"pg_index\".\"indisprimary\" IS TRUE)) WHERE ((\"pg_attribute\".\"attisdropped\" IS FALSE) AND (\"pg_attribute\".\"attnum\" > 0) AND (\"pg_class\".\"oid\" = CAST(CAST('\"bulkinator_jobs\"' AS regclass) AS oid))) ORDER BY \"pg_attribute\".\"attnum\""}
{"_schema":"infl:log:2.0","source":"unknown","service":"UNDEFINED-SERVICE","host":"27e34d1e8dfa","tag":"log","level":"INFO","time":"2022-08-28T07:26:19.734Z","message":"(0.002137s) SELECT \"pg_attribute\".\"attname\" AS \"name\", CAST(\"pg_attribute\".\"atttypid\" AS integer) AS \"oid\", CAST(\"basetype\".\"oid\" AS integer) AS \"base_oid\", format_type(\"basetype\".\"oid\", \"pg_type\".\"typtypmod\") AS \"db_base_type\", format_type(\"pg_type\".\"oid\", \"pg_attribute\".\"atttypmod\") AS \"db_type\", pg_get_expr(\"pg_attrdef\".\"adbin\", \"pg_class\".\"oid\") AS \"default\", NOT \"pg_attribute\".\"attnotnull\" AS \"allow_null\", COALESCE((\"pg_attribute\".\"attnum\" = ANY(\"pg_index\".\"indkey\")), false) AS \"primary_key\" FROM \"pg_class\" INNER JOIN \"pg_attribute\" ON (\"pg_attribute\".\"attrelid\" = \"pg_class\".\"oid\") INNER JOIN \"pg_type\" ON (\"pg_type\".\"oid\" = \"pg_attribute\".\"atttypid\") LEFT OUTER JOIN \"pg_type\" AS \"basetype\" ON (\"basetype\".\"oid\" = \"pg_type\".\"typbasetype\") LEFT OUTER JOIN \"pg_attrdef\" ON ((\"pg_attrdef\".\"adrelid\" = \"pg_class\".\"oid\") AND (\"pg_attrdef\".\"adnum\" = \"pg_attribute\".\"attnum\")) LEFT OUTER JOIN \"pg_index\" ON ((\"pg_index\".\"indrelid\" = \"pg_class\".\"oid\") AND (\"pg_index\".\"indisprimary\" IS TRUE)) WHERE ((\"pg_attribute\".\"attisdropped\" IS FALSE) AND (\"pg_attribute\".\"attnum\" > 0) AND (\"pg_class\".\"oid\" = CAST(CAST('\"bulkinator_job_items\"' AS regclass) AS oid))) ORDER BY \"pg_attribute\".\"attnum\""}
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /opt/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/src/app/config/initializers/fast_gettext.rb:16: warning: already initialized constant FastGettext::LOCALE_REX
/opt/bundle/gems/fast_gettext-2.0.0/lib/fast_gettext.rb:14: warning: previous definition of LOCALE_REX was here
/usr/src/app/config/initializers/opentelemetry.rb:12: warning: already initialized constant OpenTelemetry::Instrumentation::PG::Instrumentation::MINIMUM_VERSION
/opt/bundle/gems/opentelemetry-instrumentation-pg-0.19.2/lib/opentelemetry/instrumentation/pg/instrumentation.rb:12: warning: previous definition of MINIMUM_VERSION was here
I, [2022-08-28T07:26:19.846391 #1]  INFO -- : Instrumentation: OpenTelemetry::Instrumentation::ConcurrentRuby was successfully installed
I, [2022-08-28T07:26:19.847233 #1]  INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Faraday was successfully installed
I, [2022-08-28T07:26:19.847796 #1]  INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Net::HTTP was successfully installed
I, [2022-08-28T07:26:19.849491 #1]  INFO -- : Instrumentation: OpenTelemetry::Instrumentation::PG was successfully installed
I, [2022-08-28T07:26:19.850746 #1]  INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Rack was successfully installed
I, [2022-08-28T07:26:19.851402 #1]  INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Redis was successfully installed
I, [2022-08-28T07:26:19.853377 #1]  INFO -- : Instrumentation: OpenTelemetry::Instrumentation::Sidekiq was successfully installed
/opt/bundle/gems/pyroscope-0.4.0-x86_64-linux/lib/pyroscope.rb:71: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0067 p:---- s:0378 e:000377 CFUNC  :initialize_agent
c:0066 p:0268 s:0364 e:000363 METHOD /opt/bundle/gems/pyroscope-0.4.0-x86_64-linux/lib/pyroscope.rb:71
c:0065 p:0018 s:0360 e:000359 TOP    /usr/src/app/config/initializers/pyroscope.rb:3 [FINISH]
c:0064 p:---- s:0357 e:000356 CFUNC  :load
c:0063 p:0034 s:0351 e:000350 METHOD /opt/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55
c:0062 p:0011 s:0342 e:000341 BLOCK  /opt/bundle/gems/activesupport-4.2.11.17/lib/active_support/dependencies.rb:268
c:0061 p:0051 s:0339 e:000338 METHOD /opt/bundle/gems/activesupport-4.2.11.17/lib/active_support/dependencies.rb:240
c:0060 p:0015 s:0333 e:000332 METHOD /opt/bundle/gems/activesupport-4.2.11.17/lib/active_support/dependencies.rb:268
c:0059 p:0007 s:0326 e:000325 BLOCK  /opt/bundle/gems/railties-4.2.11.17/lib/rails/engine.rb:652
c:0058 p:0038 s:0323 e:000322 METHOD /opt/bundle/gems/activesupport-4.2.11.17/lib/active_support/notifications.rb:166
c:0057 p:0017 s:0317 e:000316 METHOD /opt/bundle/gems/railties-4.2.11.17/lib/rails/engine.rb:651
c:0056 p:0007 s:0312 e:000311 BLOCK  /opt/bundle/gems/railties-4.2.11.17/lib/rails/engine.rb:616 [FINISH]
c:0055 p:---- s:0308 e:000307 CFUNC  :each
c:0054 p:0022 s:0304 E:0015f0 BLOCK  /opt/bundle/gems/railties-4.2.11.17/lib/rails/engine.rb:615 [FINISH]
c:0053 p:---- s:0301 e:000300 CFUNC  :instance_exec
c:0052 p:0015 s:0296 E:001658 METHOD /opt/bundle/gems/railties-4.2.11.17/lib/rails/initializable.rb:30
c:0051 p:0019 s:0291 E:001688 BLOCK  /opt/bundle/gems/railties-4.2.11.17/lib/rails/initializable.rb:55
c:0050 p:0019 s:0287 E:0016b8 BLOCK  /usr/local/lib/ruby/2.5.0/tsort.rb:228
c:0049 p:0005 s:0283 E:0016e8 BLOCK  /usr/local/lib/ruby/2.5.0/tsort.rb:350
c:0048 p:0005 s:0279 E:001718 BLOCK  /usr/local/lib/ruby/2.5.0/tsort.rb:422
c:0047 p:0109 s:0275 E:0006a0 METHOD /usr/local/lib/ruby/2.5.0/tsort.rb:431
c:0046 p:0059 s:0263 E:001438 BLOCK  /usr/local/lib/ruby/2.5.0/tsort.rb:421 [FINISH]
c:0045 p:---- s:0257 e:000256 CFUNC  :each
c:0044 p:0011 s:0253 E:001750 METHOD /opt/bundle/gems/railties-4.2.11.17/lib/rails/initializable.rb:44 [FINISH]
c:0043 p:---- s:0247 e:000246 CFUNC  :call
c:0042 p:0075 s:0242 E:000fb0 METHOD /usr/local/lib/ruby/2.5.0/tsort.rb:415
c:0041 p:0031 s:0230 E:0016b8 BLOCK  /usr/local/lib/ruby/2.5.0/tsort.rb:349 [FINISH]
c:0040 p:---- s:0226 e:000225 CFUNC  :each
c:0039 p:---- s:0223 e:000222 CFUNC  :call
c:0038 p:0033 s:0219 E:000900 METHOD /usr/local/lib/ruby/2.5.0/tsort.rb:347
c:0037 p:0034 s:0211 E:000880 METHOD /usr/local/lib/ruby/2.5.0/tsort.rb:226
c:0036 p:0033 s:0205 E:0004b8 METHOD /usr/local/lib/ruby/2.5.0/tsort.rb:205
c:0035 p:0022 s:0198 E:000810 METHOD /opt/bundle/gems/railties-4.2.11.17/lib/rails/initializable.rb:54
c:0034 p:0023 s:0192 E:000788 METHOD /opt/bundle/gems/railties-4.2.11.17/lib/rails/application.rb:352
c:0033 p:0032 s:0187 E:001090 TOP    /usr/src/app/config/environment.rb:6 [FINISH]
c:0032 p:---- s:0184 e:000183 CFUNC  :require
c:0031 p:0047 s:0179 E:0010f0 BLOCK  config.ru:8 [FINISH]
c:0030 p:---- s:0176 e:000175 CFUNC  :instance_eval
c:0029 p:0034 s:0172 E:001160 METHOD /opt/bundle/gems/rack-1.6.13/lib/rack/builder.rb:55 [FINISH]
c:0028 p:---- s:0166 e:000165 CFUNC  :new
c:0027 p:0013 s:0162 E:0010c0 EVAL   [FINISH]
c:0026 p:---- s:0159 e:000158 CFUNC  :eval
c:0025 p:0030 s:0151 E:0011a0 METHOD /opt/bundle/gems/rack-1.6.13/lib/rack/builder.rb:49
c:0024 p:0090 s:0145 E:0011f8 METHOD /opt/bundle/gems/rack-1.6.13/lib/rack/builder.rb:40
c:0023 p:0053 s:0136 E:001238 METHOD /opt/bundle/gems/puma-5.0.4/lib/puma/configuration.rb:331
c:0022 p:0017 s:0129 E:001270 METHOD /opt/bundle/gems/puma-5.0.4/lib/puma/configuration.rb:257
c:0021 p:0033 s:0123 E:0012a8 METHOD /opt/bundle/gems/puma-5.0.4/lib/puma/runner.rb:131
c:0020 p:0011 s:0118 E:0012e0 METHOD /opt/bundle/gems/puma-5.0.4/lib/puma/single.rb:44
c:0019 p:0119 s:0112 E:001328 METHOD /opt/bundle/gems/puma-5.0.4/lib/puma/launcher.rb:171
c:0018 p:0006 s:0105 E:001350 METHOD /opt/bundle/gems/puma-5.0.4/lib/puma/cli.rb:80
c:0017 p:0033 s:0101 E:001388 TOP    /opt/bundle/gems/puma-5.0.4/bin/puma:10 [FINISH]
c:0016 p:---- s:0097 e:000096 CFUNC  :load
c:0015 p:0109 s:0092 E:0013c0 TOP    /opt/bundle/bin/puma:23 [FINISH]
c:0014 p:---- s:0087 e:000086 CFUNC  :load
c:0013 p:0128 s:0082 E:001418 METHOD /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74
c:0012 p:0075 s:0073 E:001448 METHOD /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28
c:0011 p:0026 s:0068 E:001478 METHOD /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463
c:0010 p:0064 s:0063 E:0014c0 METHOD /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27
c:0009 p:0047 s:0055 E:001508 METHOD /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126
c:0008 p:0261 s:0048 E:0021b8 METHOD /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387
c:0007 p:0010 s:0035 E:001538 METHOD /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27
c:0006 p:0064 s:0030 E:0015a8 METHOD /usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466
c:0005 p:0010 s:0023 E:0015e0 METHOD /usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18
c:0004 p:0079 s:0017 E:001628 BLOCK  /usr/local/bin/bundle:30
c:0003 p:0002 s:0011 E:001688 METHOD /usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124
c:0002 p:0046 s:0006 E:000aa0 EVAL   /usr/local/bin/bundle:22 [FINISH]
c:0001 p:0000 s:0003 E:0000f0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/local/bin/bundle:22:in `<main>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
/opt/bundle/bin/puma:23:in `<top (required)>'
/opt/bundle/bin/puma:23:in `load'
/opt/bundle/gems/puma-5.0.4/bin/puma:10:in `<top (required)>'
/opt/bundle/gems/puma-5.0.4/lib/puma/cli.rb:80:in `run'
/opt/bundle/gems/puma-5.0.4/lib/puma/launcher.rb:171:in `run'
/opt/bundle/gems/puma-5.0.4/lib/puma/single.rb:44:in `run'
/opt/bundle/gems/puma-5.0.4/lib/puma/runner.rb:131:in `load_and_bind'
/opt/bundle/gems/puma-5.0.4/lib/puma/configuration.rb:257:in `app'
/opt/bundle/gems/puma-5.0.4/lib/puma/configuration.rb:331:in `load_rackup'
/opt/bundle/gems/rack-1.6.13/lib/rack/builder.rb:40:in `parse_file'
/opt/bundle/gems/rack-1.6.13/lib/rack/builder.rb:49:in `new_from_string'
/opt/bundle/gems/rack-1.6.13/lib/rack/builder.rb:49:in `eval'
config.ru:0:in `<main>'
config.ru:0:in `new'
/opt/bundle/gems/rack-1.6.13/lib/rack/builder.rb:55:in `initialize'
/opt/bundle/gems/rack-1.6.13/lib/rack/builder.rb:55:in `instance_eval'
config.ru:8:in `block in <main>'
config.ru:8:in `require'
/usr/src/app/config/environment.rb:6:in `<top (required)>'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/application.rb:352:in `initialize!'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:415:in `call'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/initializable.rb:44:in `each'
/usr/local/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/initializable.rb:30:in `run'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/initializable.rb:30:in `instance_exec'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/engine.rb:615:in `each'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/bundle/gems/activesupport-4.2.11.17/lib/active_support/notifications.rb:166:in `instrument'
/opt/bundle/gems/railties-4.2.11.17/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/bundle/gems/activesupport-4.2.11.17/lib/active_support/dependencies.rb:268:in `load'
/opt/bundle/gems/activesupport-4.2.11.17/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bundle/gems/activesupport-4.2.11.17/lib/active_support/dependencies.rb:268:in `block in load'
/opt/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/opt/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/usr/src/app/config/initializers/pyroscope.rb:3:in `<top (required)>'
/opt/bundle/gems/pyroscope-0.4.0-x86_64-linux/lib/pyroscope.rb:71:in `configure'
/opt/bundle/gems/pyroscope-0.4.0-x86_64-linux/lib/pyroscope.rb:71:in `initialize_agent'

-- Machine register context ------------------------------------------------
 RIP: 0x00007ff8cc87a857 RBP: 0x00007fff205e2bd0 RSP: 0x00007fff205e2b78
 RAX: 0x00007ff8cc8c6eb0 RBX: 0x0000000000000000 RCX: 0x00007ff8cd2511c7
 RDX: 0x0000000000000040 RDI: 0x00007ff8cc902623 RSI: 0x00007ff8cc902718
  R8: 0x0000000000000000  R9: 0x000055fe5fdcfae0 R10: 0x000055fe55268010
 R11: 0x0000000000000246 R12: 0x0000000000000000 R13: 0x000055fe5fdcf660
 R14: 0x00007fff205e2d50 R15: 0x00007fff205e2c08 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/usr/local/lib/libruby.so.2.5(rb_vm_bugreport+0x50d) [0x7ff8cd7a548d]
/usr/local/lib/libruby.so.2.5(0xa7868) [0x7ff8cd631868]
/usr/local/lib/libruby.so.2.5(0x193a02) [0x7ff8cd71da02]
/lib/x86_64-linux-gnu/libpthread.so.0(0x7ff8cd571730) [0x7ff8cd571730]
/lib/libc.musl-x86_64.so.1(0x7ff8cc87a857) [0x7ff8cc87a857]
```

**Comment by Alibirb** [comment]
I think you may have put this bug report in the wrong repo. This is a library for Rust, not Ruby.
